CyGateWMS/Controllers/TypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CyGateWMS.Models;
using Microsoft.AspNetCore.Authorization;

namespace CyGateWMS.Controllers
{
    [Authorize]
    public class TypeController : Controller
    {
        private readonly CygateWMSContext _context;

        public TypeController(CygateWMSContext context)
        {
            _context = context;
        }

        // GET: CustomerCatagories
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Type.ToListAsync());
        }

        // GET: CustomerCatagories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var type = await _context.Type
                .FirstOrDefaultAsync(m => m.TypeId == id);
            if (type == null)
            {
                return NotFound();
            }

            return View(type);
        }

        // GET: CustomerCatagories/Create
        [Authorize(Constants.ADMIN)]
        public IActionResult Create()
        {
            return View();
        }

        // POST: CustomerCatagories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Constants.ADMIN)]
        public async Task<IActionResult> Create(Models.Type type)
        {
            if (ModelState.IsValid)
            {
                type.IsActive = true;
                type.CreatedOn = DateTime.Now;
                _context.Add(type);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(type);
        }

        // GET: CustomerCatagories/Edit/5
        [Authorize(Constants.ADMIN)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var type = await _context.Type.FindAsync(id);
            if (type == null)
            {
                return NotFound();
            }
            return View(type);
        }

        // POST: CustomerCatagories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Constants.ADMIN)]
        public async Task<IActionResult> Edit(int id, Models.Type type)
        {
            if (id != type.TypeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var _type = await _context.Type.FindAsync(id);
                    _type.ModifiedOn = DateTime.Now;
                    _type.TypeName = type.TypeName;
                    _type.FilterValue = type.FilterValue;
                    _type.IsActive = type.IsActive;
                    _context.Update(_type);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerCatagoriesExists(type.TypeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(type);
        }

        // GET: CustomerCatagories/Delete/5
        [Authorize(Constants.ADMIN)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customerCatagories = await _context.Type
                .FirstOrDefaultAsync(m => m.TypeId == id);
            if (customerCatagories == null)
            {
                return NotFound();
            }

            return View(customerCatagories);
        }

        // POST: CustomerCatagories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Constants.ADMIN)]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var type = await _context.Type.FindAsync(id);
            _context.Type.Remove(type);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerCatagoriesExists(int id)
        {
            return _context.Type.Any(e => e.TypeId == id);
        }
    }
}

CyGateWMS/Views/Type/Create.cshtml
@model CyGateWMS.Models.Type

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_DashBoard_Layout.cshtml";
}



<div class="header">
    <hr />
    <ol class="breadcrumb">
        <li><a asp-controller="Type" asp-action="Index">Type</a></li>
    </ol>

</div>

<div id="page-inner">
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" asp-action="Create" role="form" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="TypeName" class="col-sm-2 control-label">Type</label>
                            <div class="col-sm-10">
                                <input asp-for="TypeName" type="text" class="form-control">
                            </div>
                            <span asp-validation-for="TypeName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="FilterValue" class="col-sm-2 control-label">Key</label>
                            <div class="col-sm-10">
                                <input asp-for="FilterValue" type="text" class="form-control">
                            </div>
                            <span asp-validation-for="FilterValue" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-default">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

CyGateWMS/Views/Type/Delete.cshtml
@model CyGateWMS.Models.Type

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_DashBoard_Layout.cshtml";
}

<hr />
<div class="header">
    <ol class="breadcrumb">
        <li><a asp-action="Index" asp-controller="Category">Type</a></li>
        <li class="active">@Model.TypeName</li>
    </ol>

</div>

<div id="page-inner">
    <div class="row">
        <div class="col-md-12">
            <!-- Advanced Tables -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    @Model.TypeName
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">

                            <table class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example" aria-describedby="dataTables-example_info">


                                <tbody>
                                    <tr class="gradeA odd">
                                        <td class="sorting_1"> Catagories Name</td>
                                        <td class="center ">@Html.DisplayFor(model => model.TypeName)</td>
                                    </tr>
                                    <tr class="gradeA even">
                                        <td class="sorting_1"> Created On</td>
                                        <td class="center ">@Html.DisplayFor(model => model.CreatedOn)</td>
                                    </tr>
                                    <tr class="gradeA odd">
                                        <td class="sorting_1"> Modified On</td>
                                        <td class="center ">@Html.DisplayFor(model => model.ModifiedOn)</td>
                                    </tr>
                                    <tr class="gradeA odd">
                                        <td class="sorting_1"> Status</td>
                                        <td class="center ">@(Model.IsActive ? "Active" : "InActive")</td>
                                    </tr>
                                    <tr class="gradeA even">
                                        <td class="sorting_1"> Key</td>
                                        <td class="center ">@Html.DisplayFor(model => model.FilterValue)</td>
                                    </tr>
                                </tbody>
                            </table><div class="row">
                            </div>
                        </div>
                        <div>
                            <form asp-action="Delete">
                                <input type="hidden" asp-for="TypeId" />
                                <input type="submit" value="Delete" class="btn btn-default" /> |
                                <a asp-action="Index">Back to List</a>
                            </form>
                        </div>
                    </div>
                </div>
                <!--End Advanced Tables -->
            </div>
        </div>
    </div>
</div>

CyGateWMS/Views/Type/Details.cshtml
@model CyGateWMS.Models.Type

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_DashBoard_Layout.cshtml";
}

<hr />
<div class="header">
    <ol class="breadcrumb">
        <li><a asp-action="Index" asp-controller="Type">Type</a></li>
        <li class="active">@Model.TypeName</li>
    </ol>

</div>

<div id="page-inner">
    <div class="row">
        <div class="col-md-12">
            <!-- Advanced Tables -->
            <div class="panel panel-default">
                <div class="panel-heading">

                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">

                            <table class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example" aria-describedby="dataTables-example_info">


                                <tbody>
                                    <tr class="gradeA odd">
                                        <td class="sorting_1">Catagories Name</td>
                                        <td class="center ">@Html.DisplayFor(model => model.TypeName)</td>
                                    </tr>
                                    <tr class="gradeA even">
                                        <td class="sorting_1"> Created On</td>
                                        <td class="center ">@Html.DisplayFor(model => model.CreatedOn)</td>
                                    </tr>
                                    <tr class="gradeA odd">
                                        <td class="sorting_1"> Modified On</td>
                                        <td class="center ">@Html.DisplayFor(model => model.ModifiedOn)</td>
                                    </tr>
                                    <tr class="gradeA even">
                                        <td class="sorting_1"> Status</td>
                                        <td class="center ">@(Model.IsActive ? "Active" : "InActive")</td>
                                    </tr>
                                    <tr class="gradeA odd">
                                        <td class="sorting_1"> Key</td>
                                        <td class="center ">@Html.DisplayFor(model => model.FilterValue)</td>
                                    </tr>
                                </tbody>
                            </table><div class="row">
                            </div>
                        </div>
                        <div>
                            <a asp-action="Edit" asp-route-id="@Model.TypeId">Edit</a> |
                            <a asp-action="Index">Back to List</a>
                        </div>
                    </div>
                </div>
                <!--End Advanced Tables -->
            </div>
        </div>
    </div>
</div>

CyGateWMS/Views/Type/Edit.cshtml
@model CyGateWMS.Models.Type

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_DashBoard_Layout.cshtml";
}

<div class="header">
    <hr />
    <ol class="breadcrumb">
        <li><a asp-controller="Category" asp-action="Index">Type</a></li>
        <li class="active">@Model.TypeName</li>
    </ol>

</div>

<div id="page-inner">
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" asp-action="Edit" role="form" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="TypeId" />
                        <div class="form-group">
                            <label asp-for="TypeName" class="col-sm-2 control-label">Type</label>
                            <div class="col-sm-10">
                                <input asp-for="TypeName" type="text" class="form-control">
                            </div>
                            <span asp-validation-for="TypeName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="FilterValue" class="col-sm-2 control-label">Key</label>
                            <div class="col-sm-10">
                                <input asp-for="FilterValue" type="text" class="form-control">
                            </div>
                            <span asp-validation-for="FilterValue" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="IsActive" class="col-sm-2 control-label">Status</label>
                            <div class="col-sm-1">
                                <input asp-for="IsActive" type="checkbox" class="form-control">
                            </div>
                            <span asp-validation-for="IsActive" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-default">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

CyGateWMS/Views/Type/Index.cshtml
@model IEnumerable<CyGateWMS.Models.Type>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_DashBoard_Layout.cshtml";
}

<hr />

<div class="header">
    <ol class="breadcrumb">
        <li><a asp-action="Index" asp-controller="Type">Type</a></li>
    </ol>

</div>

<div id="page-inner">

    <div class="row">
        <div class="col-md-12">
            <!-- Advanced Tables -->
            <div class="panel panel-default">
                @if (User.IsInRole(Constants.ADMIN))
                {
                    <div class="panel-heading">
                        <a class="btn btn-info" asp-action="Create" asp-controller="Type">Add New</a>
                    </div>
                }
                @if (Model.Count() > 0)
                {
                    <div class="panel-body">
                        <div class="table-responsive">
                            <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                                <table class="table table-striped table-bordered" id="dataTable" style="width:100%;">
                                    <thead>
                                        <tr>
                                            <th>Type</th>
                                            <th>Created On</th>
                                            <th>Status</th>
                                            <th>Key</th>
                                            @if (User.IsInRole(Constants.ADMIN))
                                            {
                                                <th></th>
                                            }
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                        <tr>
                                            <td>@Html.DisplayFor(modelItem => item.TypeName)</td>
                                            <td data-order="@item.CreatedOn.ToString("yyyy-MM-dd")">@item.CreatedOn.ToString("dd-MM-yyyy")</td>
                                            <td>@((item.IsActive == true) ? "Active" : "InActive" )</td>
                                            <td>@Html.DisplayFor(modelItem => item.FilterValue)</td>
                                            @if (User.IsInRole(Constants.ADMIN))
                                            {
                                                <td>
                                                    <a class="btn btn-info" asp-action="Edit" asp-route-id="@item.TypeId">Edit</a> |
                                                    <a class="btn btn-info" asp-action="Details" asp-route-id="@item.TypeId">Details</a> |
                                                    <a class="btn btn-info" asp-action="Delete" asp-route-id="@item.TypeId">Delete</a>
                                                </td>
                                            }
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>

                    </div>
                }
            </div>
            <!--End Advanced Tables -->
        </div>
    </div>
</div>