CyGateWMS/Models/ApplicationRole.cs
using Microsoft.AspNetCore.Identity;
using System;

namespace CyGateWMS.Models
{
    public class ApplicationRole : IdentityRole
    {
        public string Description { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedOn { get; set; }
        public string IPAddress { get; set; }
        public bool IsActive { get; set; }
    }
}

CyGateWMS/Controllers/ApplicationRoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CyGateWMS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace CyGateWMS.Controllers
{
    [Authorize]
    public class ApplicationRoleController : Controller
    {
        private readonly CygateWMSContext _context;
        private readonly RoleManager<ApplicationRole> roleManager;

        public ApplicationRoleController(CygateWMSContext context, RoleManager<ApplicationRole> roleManager)
        {
            this._context = context;
            this.roleManager = roleManager;
        }

        // GET: Roles
        public async Task<IActionResult> Index()
        {
            return View(await roleManager.Roles.ToListAsync());
        }

        // GET: Roles/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // GET: Roles/Create
        [Authorize(Constants.ADMIN)]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Roles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Constants.ADMIN)]
        public async Task<IActionResult> Create([Bind("Description,Name")] ApplicationRole role)
        {
            if (ModelState.IsValid)
            {
                role.IPAddress = Request.HttpContext.Connection.RemoteIpAddress.ToString();
                role.CreatedDate = DateTime.Now;
                role.IsActive = true;
                IdentityResult roleRuslt =  await roleManager.CreateAsync(role);
                if (roleRuslt.Succeeded)
                {
                    return RedirectToAction(nameof(Index));
                }                
            }
            
            return View(role);
        }

        // GET: Roles/Edit/5
        [Authorize(Constants.ADMIN)]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            return View(role);
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Constants.ADMIN)]
        public async Task<IActionResult> Edit(string id, ApplicationRole role)
        {
            if (id != role.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var roleTemp = await roleManager.FindByIdAsync(id);
                    roleTemp.Description = role.Description;
                    roleTemp.IsActive = role.IsActive;
                    roleTemp.ModifiedOn = DateTime.Now;
                    await roleManager.UpdateAsync(roleTemp);
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    if (roleManager.FindByIdAsync(role.Id) == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }

        // GET: Roles/Delete/5
        [Authorize(Constants.ADMIN)]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }

            return View(role);
        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Constants.ADMIN)]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var role = await roleManager.FindByIdAsync(id);
            await roleManager.DeleteAsync(role);
            return RedirectToAction(nameof(Index));
        }
        
    }
}

CyGateWMS/Views/ApplicationRole/Create.cshtml
@model CyGateWMS.Models.ApplicationRole

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_DashBoard_Layout.cshtml";
}


<div class="header">
    <hr />
    <ol class="breadcrumb">
        <li><a asp-controller="ApplicationRole" asp-action="Index">Role</a></li>
    </ol>

</div>

<div id="page-inner">
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" asp-action="Create" role="form" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Name" class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-10">
                                <input asp-for="Name" type="text" class="form-control">
                            </div>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="col-sm-2 control-label">Description</label>
                            <div class="col-sm-10">
                                <input asp-for="Description" type="text" class="form-control">
                            </div>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-default">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

CyGateWMS/Views/ApplicationRole/Details.cshtml
@model CyGateWMS.Models.ApplicationRole

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_DashBoard_Layout.cshtml";
}

    <hr />
    <div class="header">
        <ol class="breadcrumb">
            <li><a asp-action="Index" asp-controller="ApplicationRoles">Roles</a></li>
            <li><a asp-action="Index" asp-controller="ApplicationRoles" class="active">@Model.Name</a></li>
        </ol>

    </div>

    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <!-- Advanced Tables -->
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Advanced Tables
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">

                                <table class="table table-striped table-bordered table-hover dataTable no-footer" id="dataTables-example" aria-describedby="dataTables-example_info">


                                    <tbody>
                                        <tr class="gradeA odd">
                                            <td class="sorting_1"> @Html.DisplayNameFor(model => model.Description)</td>
                                            <td class="center ">@Html.DisplayFor(model => model.Description)</td>
                                        </tr>
                                        <tr class="gradeA even">
                                            <td class="sorting_1"> @Html.DisplayNameFor(model => model.Name)</td>
                                            <td class="center ">@Html.DisplayFor(model => model.Name)</td>
                                        </tr>
                                        <tr class="gradeA even">
                                            <td class="sorting_1"> @Html.DisplayNameFor(model => model.CreatedDate)</td>
                                            <td class="center ">@Html.DisplayFor(model => model.CreatedDate)</td>
                                        </tr>
                                        <tr class="gradeA even">
                                            <td class="sorting_1"> @Html.DisplayNameFor(model => model.IsActive)</td>
                                            <td class="center ">@Html.DisplayFor(model => model.IsActive)</td>
                                        </tr>
                                        <tr class="gradeA even">
                                            <td class="sorting_1"> @Html.DisplayNameFor(model => model.Id)</td>
                                            <td class="center ">@Html.DisplayFor(model => model.Id)</td>
                                        </tr>
                                    </tbody>
                                </table><div class="row">
                                </div>
                            </div>
                            <div>
                                <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
                                <a asp-action="Index">Back to List</a>
                            </div>
                        </div>
                </div>
                <!--End Advanced Tables -->
            </div>
        </div>
</div>
    </div>

CyGateWMS/Views/ApplicationRole/Edit.cshtml
@model CyGateWMS.Models.ApplicationRole

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_DashBoard_Layout.cshtml";
}

<div class="header">
    <hr/>
    <ol class="breadcrumb">
        <li><a asp-controller="ApplicationRole" asp-action="Index">Roles</a></li>
        <li class="active">@Model.Name</li>
    </ol>

</div>

<div id="page-inner">
    <div class="row">
        <div class="col-xs-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                </div>
                <div class="panel-body">
                    <form class="form-horizontal" asp-action="Edit" role="form" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Name" class="col-sm-2 control-label">Name</label>
                            <div class="col-sm-10">
                                <input asp-for="Name" type="text" class="form-control">
                            </div>
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Description" class="col-sm-2 control-label">Description</label>
                            <div class="col-sm-10">
                                <input asp-for="Description" type="text" class="form-control">
                            </div>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="IsActive" class="col-sm-2 control-label">Status</label>
                            <div class="col-sm-1">
                                <input asp-for="IsActive" type="checkbox" class="form-control">
                            </div>
                            <span asp-validation-for="IsActive" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-default">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

CyGateWMS/Views/ApplicationRole/Index.cshtml
@model IEnumerable<CyGateWMS.Models.ApplicationRole>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_DashBoard_Layout.cshtml";
}

<hr/>

<div class="header">
    <ol class="breadcrumb">
        <li><a asp-action="Index" asp-controller="ApplicationRoles">Roles</a></li>
    </ol>

</div>

<div id="page-inner">

    <div class="row">
        <div class="col-md-12">
            <!-- Advanced Tables -->
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a class="btn btn-info" asp-action="Create" asp-controller="ApplicationRole">Add New</a>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline" role="grid">
                            <table class="table table-striped table-bordered" id="dataTable" style="width:100%;">
                                <thead>
                                    <tr>
                                        <th>@Html.DisplayNameFor(model => model.Name)</th>
                                        <th>@Html.DisplayNameFor(model => model.Description)</th>
                                        <th>Status</th>
                                        <th>Created On</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                    <tr>
                                        <td> @Html.DisplayFor(modelItem => item.Name)</td>
                                        <td> @Html.DisplayFor(modelItem => item.Description)</td>
                                        <td> @(item.IsActive ? "Active" : "InActive")</td>
                                        <td data-order="@item.CreatedDate.ToString("yyyy-MM-dd")">@item.CreatedDate.ToString("dd-MM-yyyy")</td>
                                        <td>
                                            <a class="btn btn-info" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                                            <a class="btn btn-info" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                                            <a class="btn btn-info" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                        </td>
                                    </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>

                </div>
            </div>
            <!--End Advanced Tables -->
        </div>
        </div>
    </div>